name: API Test Automation

on:
  workflow_dispatch:
    inputs:
      subscription:
        description: 'Scopes'
        required: true
        default: 'regression'
        type: choice
        options:
          - smoke
          - regression

  push:
    branches:
      - master

  schedule:
    - cron: '0 8 * * 1-5'  # Будние дни в 8:00 UTC

jobs:
  pytest-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests based on scope
        run: |
          echo "Selected subscription: ${{ github.event.inputs.subscription }}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            pytest -m ${{ github.event.inputs.subscription }} --junitxml=result.xml --disable-warnings -v
          else
            pytest --junitxml=result.xml --disable-warnings -v
          fi

      - name: Upload JUnit XML report
        uses: actions/upload-artifact@v2
        with:
          name: junit-report
          path: result.xml
