name: API Test Automation

on:
  workflow_dispatch:
    inputs:
      subscription:
        description: 'Scopes'
        required: true
        default: 'regression'
        type: choice
        options:
          - smoke
          - regression

  push:
    branches:
      - main

  schedule:
    - cron: '0 8 * * 1-5'  # Будние дни в 8:00 UTC

permissions:
  checks: write
  contents: read

jobs:
  pytest-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Running tests with scope: ${{ github.event.inputs.subscription }}"
            pytest -m ${{ github.event.inputs.subscription }} --alluredir=allure-results --disable-warnings -v
          else
            echo "Running full test suite"
            pytest --alluredir=allure-results --disable-warnings -v
          fi

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
        continue-on-error: true

      - name: Publish Allure Test Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: 'result.xml'